[package]
name = "logkit"
version = "0.1.0"
edition = "2021"
authors = ["Jian Chen <admin@chensoft.com>"]
license = "MIT"
description = "A brand new logging library"
documentation = "https://docs.rs/logkit"
repository = "https://github.com/chensoft/logkit"
readme = "README.md"
keywords = ["logkit", "log", "logger", "logging"]

[dependencies]
