[package]
name = "logkit"
version = "0.3.6"
edition = "2021"
authors = ["Jian Chen <admin@chensoft.com>"]
license = "MIT"
description = "Super fast, structured, scalable logging library for Rust"
documentation = "https://docs.rs/logkit"
repository = "https://github.com/chensoft/logkit"
readme = "README.md"
keywords = ["log", "logger", "logging"]

[features]
default = ["trace", "debug", "info", "warn", "error"]
trace = []
debug = []
info = []
warn = []
error = []

[dependencies]
time = { version = "0.3", features = ["local-offset", "formatting"] }
encoder = "0.2"
backtrace = "0.3"

[dev-dependencies]
tokio = { version = "1.38", features = ["full"] }
futures = "0.3"
criterion = "0.5"

[[bench]]
name = "benchmark"
harness = false
